# Generated by Django 3.2.9 on 2022-03-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lehrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ski_level', models.CharField(choices=[('0', 'Keine Kentnisse'), ('1', 'Ausbildungswochenende mitgemacht'), ('2', 'DSV Grundstufe/DSLV Level 2'), ('3', 'DSV Instructor/DSLV Level 3'), ('4', 'DSV Skilehrer/Staatlich geprüfter Skilehrer')], default='0', max_length=2)),
                ('snowboard_level', models.CharField(choices=[('0', 'Keine Kentnisse'), ('1', 'Ausbildungswochenende mitgemacht'), ('2', 'DSV Grundstufe/DSLV Level 2'), ('3', 'DSV Instructor/DSLV Level 3'), ('4', 'DSV Skilehrer/Staatlich geprüfter Skilehrer')], default='0', max_length=2)),
                ('telemark_level', models.CharField(choices=[('0', 'Keine Kentnisse'), ('1', 'Ausbildungswochenende mitgemacht'), ('2', 'DSV Grundstufe/DSLV Level 2'), ('3', 'DSV Instructor/DSLV Level 3'), ('4', 'DSV Skilehrer/Staatlich geprüfter Skilehrer')], default='0', max_length=2)),
                ('langlauf_level', models.CharField(choices=[('0', 'Keine Kentnisse'), ('1', 'Ausbildungswochenende mitgemacht'), ('2', 'DSV Grundstufe/DSLV Level 2'), ('3', 'DSV Instructor/DSLV Level 3'), ('4', 'DSV Skilehrer/Staatlich geprüfter Skilehrer')], default='0', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geändert am:')),
            ],
        ),
    ]
