# Generated by Django 3.2.9 on 2022-03-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schueler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('alter', models.IntegerField(blank=True, null=True)),
                ('Skillevel_Ski', models.CharField(choices=[('0', 'Level 0'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4'), ('5', 'Level 5'), ('6', 'Level 6'), ('7', 'Level 7')], default='0', max_length=2)),
                ('Skillevel_Snowboard', models.CharField(choices=[('0', 'Level 0'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4'), ('5', 'Level 5'), ('6', 'Level 6'), ('7', 'Level 7')], default='0', max_length=2)),
                ('Skillevel_Langlauf', models.CharField(choices=[('0', 'Level 0'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4'), ('5', 'Level 5'), ('6', 'Level 6'), ('7', 'Level 7')], default='0', max_length=2)),
                ('Skillevel_Telemark', models.CharField(choices=[('0', 'Level 0'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4'), ('5', 'Level 5'), ('6', 'Level 6'), ('7', 'Level 7')], default='0', max_length=2)),
                ('telefonnummer', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
