# Generated by Django 3.2.9 on 2022-03-12 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lehrer', '0001_initial'),
        ('Kurse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='lehrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lehrer.lehrer'),
        ),
    ]
