# Generated by Django 3.2.9 on 2022-03-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schüler', '0001_initial'),
        ('Kurse', '0002_kurs_lehrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='teilnehmer',
            field=models.ManyToManyField(to='Schüler.Schueler'),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='skill_level',
            field=models.CharField(choices=[('0', 'Level 0'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4'), ('5', 'Level 5'), ('6', 'Level 6'), ('7', 'Level 7')], default='0', max_length=2),
        ),
    ]
