# Generated by Django 3.2.9 on 2022-03-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kurse', '0003_auto_20220314_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurs',
            name='time',
            field=models.CharField(choices=[('09:00', '09:00 - 10:00'), ('10:00', '10:00 - 12:00'), ('12:00', '12:00 - 13:00'), ('13:30', '13:30 - 15:30')], max_length=5),
        ),
    ]
